services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: easy-gen-auth
    volumes:
      - mongo_data:/data/db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret
      - MONGO_URI=mongodb://user:password@mongo:27017/easy-gen-auth?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    depends_on:
      - server
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  mongo_data:
